### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mhrohani1385** [cunla/ghactions-toolbar#30]
```
org.jetbrains.plugins.github.exceptions.GithubJsonException: Can't Get workflow-run jobs

Can't parse GitHub response
	at org.jetbrains.plugins.github.api.GithubApiContentHelper.readJson(GithubApiContentHelper.kt:80)
	at org.jetbrains.plugins.github.api.GithubApiContentHelper.readJsonObject(GithubApiContentHelper.kt:63)
	at org.jetbrains.plugins.github.api.GithubApiContentHelper.readJsonObject$default(GithubApiContentHelper.kt:62)
	at org.jetbrains.plugins.github.api.GithubApiRequest$Companion$parseJsonObject$1.convert(GithubApiRequest.kt:269)
	at org.jetbrains.plugins.github.api.GithubApiRequest$Companion$parseJsonObject$1.convert(GithubApiRequest.kt:267)
	at org.jetbrains.plugins.github.api.GithubApiRequestExecutor$Base$createResponse$1.readBody(GithubApiRequestExecutor.kt:202)
	at org.jetbrains.plugins.github.api.GithubApiRequest$Companion.parseJsonObject(GithubApiRequest.kt:269)
	at org.jetbrains.plugins.github.api.GithubApiRequest$Companion.access$parseJsonObject(GithubApiRequest.kt:267)
	at org.jetbrains.plugins.github.api.GithubApiRequest$Get$Json.extractResult(GithubApiRequest.kt:65)
	at org.jetbrains.plugins.github.api.GithubApiRequestExecutor$Base$execute$1.process(GithubApiRequestExecutor.kt:111)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:333)
	at org.jetbrains.plugins.github.api.GithubApiRequestExecutor$Base.execute(GithubApiRequestExecutor.kt:100)
	at org.jetbrains.plugins.github.api.GithubApiRequestExecutor$WithTokenAuth.execute(GithubApiRequestExecutor.kt:79)
	at com.dsoftware.ghtoolbar.data.DataProvider$value$1.invoke(DataProviders.kt:31)
	at com.dsoftware.ghtoolbar.data.DataProvider$value$1.invoke(DataProviders.kt:27)
	at com.dsoftware.ghtoolbar.data.DataProvider$backingValue$1.invoke(DataProviders.kt:55)
	at com.dsoftware.ghtoolbar.data.DataProvider$backingValue$1.invoke(DataProviders.kt:54)
	at com.intellij.collaboration.async.CompletableFutureUtil$submitIOTask$1$1.compute(CompletableFutureUtil.kt:58)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:66)
	at com.intellij.collaboration.async.CompletableFutureUtil$submitIOTask$1.get(CompletableFutureUtil.kt:58)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class WorkflowRunJob] value failed for JSON property conclusion due to missing (therefore NULL) value for creator parameter conclusion which is a non-nullable type
 at [Source: (BufferedReader); line: 1, column: 789] (through reference chain: WorkflowRunJobs["jobs"]->java.util.ArrayList[0]->WorkflowRunJob["conclusion"])
	at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:121)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:443)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:563)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:438)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3658)
	at org.jetbrains.plugins.github.api.GithubApiContentHelper.readJson(GithubApiContentHelper.kt:77)
	... 37 more
```

**Comment by cunla** [comment]
fixed in 1.0.3
