### ISSUE TITLE
GithubStatusCodeException: 404 Not Found

### ISSUE THREAD

**Issue by lilith** [cunla/ghactions-toolbar#34]
**Describe the bug**
Causes exception when viewing https://github.com/imazen/imageflow-dotnet-server action
Also, Does not show jobs for each commit, just a blank middle window

org.jetbrains.plugins.github.exceptions.GithubStatusCodeException: 404 Not Found - Not Found
	at org.jetbrains.plugins.github.api.GithubApiRequestExecutor$Base.checkResponseCode(GithubApiRequestExecutor.kt:172)
	at org.jetbrains.plugins.github.api.GithubApiRequestExecutor$Base.access$checkResponseCode(GithubApiRequestExecutor.kt:95)
	at org.jetbrains.plugins.github.api.GithubApiRequestExecutor$Base$execute$1.process(GithubApiRequestExecutor.kt:109)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:333)
	at org.jetbrains.plugins.github.api.GithubApiRequestExecutor$Base.execute(GithubApiRequestExecutor.kt:100)
	at org.jetbrains.plugins.github.api.GithubApiRequestExecutor$WithTokenAuth.execute(GithubApiRequestExecutor.kt:79)
	at com.dsoftware.ghtoolbar.data.DataProvider$value$1.invoke(DataProviders.kt:31)
	at com.dsoftware.ghtoolbar.data.DataProvider$value$1.invoke(DataProviders.kt:27)
	at com.dsoftware.ghtoolbar.data.DataProvider$backingValue$1.invoke(DataProviders.kt:55)
	at com.dsoftware.ghtoolbar.data.DataProvider$backingValue$1.invoke(DataProviders.kt:54)
	at com.intellij.collaboration.async.CompletableFutureUtil$submitIOTask$1$1.compute(CompletableFutureUtil.kt:58)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:66)
	at com.intellij.collaboration.async.CompletableFutureUtil$submitIOTask$1.get(CompletableFutureUtil.kt:58)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

JetBrains Rider 2022.2
Build #RD-222.3345.139, built on August 1, 2022
Licensed to ImageFlow / Lilith River
Subscription is active until May 3, 2023.
For non-commercial open source development only.
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
.NET 6.0.6
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 32
Registry:
    indexing.enable.entity.provider.based.indexing=false
    rdclient.asyncActions=false
    ide.new.project.model.index.case.sensitivity=true

Non-Bundled Plugins:
    com.intellij.resharper.StructuredLogging (2022.2.0.241)
    com.intellij.plugins.riderkeymap (201.6251.22)
    com.github.copilot (1.1.30.1887)
    com.dsoftware.ghtoolbar (1.1.0)
    io.aesy.yamllint (0.1)
    com.intellij.kubernetes (222.3345.108)

**Comment by lilith** [comment]
I think this occurs when the workflow has a .yaml parse error and no jobs are therefore created for it.

**Comment by cunla** [comment]
Which version are you using? I am trying to replicate this specific error with the repo you mentioned unsuccessfully

**Comment by cunla** [comment]
It happens when there is a workflow currently ongoing.. I am on it

**Comment by cunla** [comment]
Should be resolved in v1.1.1. Please let me know

**Comment by cunla** [comment]
@lilith can this be closed?

**Comment by lilith** [comment]
Yes, thank you so much!!
